# Generated by Django 3.0.6 on 2020-06-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_book_decription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numer_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=100)),
                ('semester', models.IntegerField()),
                ('specjalizejszyn', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_id', models.IntegerField()),
                ('sub_name', models.CharField(max_length=50)),
                ('students', models.ManyToManyField(to='myapp.Student')),
            ],
        ),
    ]
