# Generated by Django 3.0.7 on 2020-06-11 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_student_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='numer_id',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='sub_id',
        ),
    ]
