# Generated by Django 3.0.7 on 2020-06-11 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20200611_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='numer_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='sub_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
