# Generated by Django 3.0.7 on 2020-06-13 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20200611_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_username', models.CharField(max_length=50)),
                ('log_password', models.CharField(max_length=50)),
            ],
        ),
    ]
