# Generated by Django 3.0.6 on 2020-06-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Error_login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('errorlog', models.TextField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='login',
            old_name='log_password',
            new_name='Login',
        ),
        migrations.RemoveField(
            model_name='login',
            name='log_username',
        ),
        migrations.AddField(
            model_name='login',
            name='Password',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
