# Generated by Django 3.0.6 on 2020-06-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20200613_1757'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logout', models.TextField(max_length=50)),
            ],
        ),
    ]
